on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          template: terminal
          filename: metrics.terminal.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, metadata
